### ISSUE TITLE
Error in contact us bootstrap code

### ISSUE THREAD

**Issue by sonalshinde06** [LunaticPrakash/Cognizant-Handson-2022#4]
It is showing an error that dropdown is not done. Can you please run the code again and solve the error.

**Comment by LunaticPrakash** [comment]
Updated it. Do check again.

**Comment by sonalshinde06** [comment]
Error in the navigation bar code of bootstrap too. Do check that

**Comment by LunaticPrakash** [comment]
Okay will update it by today's evening.

**Comment by sonalshinde06** [comment]
ok thankyou
